apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: softserve
  annotations:
    haproxy-ingress.github.io/rewrite-target: /
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - "does.not.exist"
    secretName: "softserve-tls"
  rules:
  - host: does.not.exist
    http:
      paths:
      - path: /src
        pathType: Prefix
        backend:
          service:
            name: softserve
            port:
              number: 80
