apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: softserve-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ssd
  volumeMode: Filesystem
